### PR TITLE
[Bug Fixed #1219 ] & [Enhancement #1182]  Fixed 

### LINKED ISSUE #1219: All password type field field should be encrypted and on inspect element also its value should be in encrypted form.
- Framework Version: 0.1.6

### PR DESCRIPTION
**Pull request by shivam-webkul**
**BUGS:**

[Bug Fixed #1219 ]
All password type field field should be encrypted and on inspect element also its value should be in encrypted form.

1. Now admin login and the customer login password filed is encrypted form.

[Enhancement #1182]
At checkout if guest user entered an email that is already registered then provide an option to sign-in at time of checkout.

1.Now in the checkout page if customer already registered then in the checkout page shown the password field for login.
2.  Register customer not need to fill all checkout form.

### CODE REVIEW

File: packages/Webkul/Shop/src/Http/routes.php [hunk 1]
```diff
@@ -165,6 +165,9 @@
         //resend verification email
         Route::get('/resend/verification/{email}', 'Webkul\Customer\Http\Controllers\RegistrationController@resendVerificationEmail')->name('customer.resend.verification-email');
 
+        // for customer login checkout
+        Route::post('/custome/exist', 'Webkul\Shop\Http\Controllers\OnepageController@checkExistCustomer')->name('customer.checkout.exist');
```
Comment (prashant-webkul) [inline packages/Webkul/Shop/src/Http/routes.php]: Please correct this typo.
