### PR TITLE
Fixed #10831 - COD visible for non-COD eligible products in mixed products cart

### LINKED ISSUE #10831: [2.3] Cash on Delivery (COD) Available in Checkout for Downloadable Products when mixed product ( Simple or downloadbale ) in cart
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.3

### Issue Description

In the checkout process, when a customer adds a mix of product types — specifically a simple product and a downloadable product — the system incorrectly allows the Cash on Delivery (COD) payment method to be used.

Since downloadable products are delivered digitally, COD should not be applicable to them. In mixed product scenarios, where one product (i.e., downloadable) doesn't support COD, the entire order should restrict COD as a valid payment method to prevent fulfillment logic conflicts.

### Preconditions

At least one Simple Product and one Downloadable Product must be created and published.

Cash on Delivery (COD) payment method must be enabled from the admin panel.

Customer must be logged in.

Both product types are in stock and available on the frontend.

### Steps to reproduce

Add 1 simple product and 1 downloadable product to the cart.

Proceed to checkout → complete billing/shipping.

On the payment step, observe COD is visible and selectable.

Select COD and place the order.

Order is created with COD including a downloadable item.

### Expected Result

If the cart contains any non-COD eligible product (like downloadable or virtual), the COD payment method should not be shown at checkout.

The system should validate cart items and allow only online (prepaid) payment options.

### Actual Result

COD is still available as a payment option, even when the cart contains a downloadable product.

The order is placed successfully using COD, which creates a logical inconsistency, as downloadable items cannot be delivered physically.

### Screenshots

https://github.com/user-attachments/assets/ef1c224e-3aa4-42cc-ba15-27a3f4c5823c

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by og-khushalpatel**
## Issue Reference
Issue - #10831

## Description
Firstly I have to check if the mixed cart has got any non-stockable items so that I can make the COD option unavailable. For that i have created a new `haveNonStockableItems()` method inside `Cart.php` which returns `true` if non-stockable items are present in the cart otherwise `false`.
Then I have called this method in `CashOnDelivery.php` 's `isAvailable()` method which specifies the conditions where COD option should be made available. That's it!

## How To Test This?
Add 1 simple product and 1 downloadable product to the cart.
Proceed to checkout → complete billing/shipping.
On the payment step, observe COD is no more visible.

## Documentation
- [ ] My pull request requires an update on the documentation repository.
No change required since its just a bug fix.

## Branch Selection
- [ X ] Target Branch: 2.3

### CODE REVIEW

File: packages/Webkul/Checkout/src/Models/Cart.php [hunk 1]
```diff
@@ -138,6 +138,20 @@ public function haveStockableItems(): bool
         return false;
     }
 
+    /**
+     * Checks if cart have non stockable items.
+     */
+    public function haveNonStockableItems(): bool
```
Comment (devansh-webkul) [inline packages/Webkul/Checkout/src/Models/Cart.php]: Use this,

```php
/**
 * Checks if all cart items are stockable.
 */
public function hasOnlyStockableItems(): bool
{
    foreach ($this->items as $item) {
        if (! $item->product->isStockable()) {
            return false;
        }
    }

    return true;
}
```

File: packages/Webkul/Payment/src/Payment/CashOnDelivery.php [hunk 2]
```diff
@@ -31,7 +31,7 @@ public function isAvailable()
             $this->setCart();
         }
 
-        return $this->getConfigData('active') && $this->cart?->haveStockableItems();
+        return $this->getConfigData('active') && $this->cart?->haveStockableItems() && ! $this->cart?->haveNonStockableItems();
```
Comment (devansh-webkul) [inline packages/Webkul/Payment/src/Payment/CashOnDelivery.php]: Then replace this with,

```php
return $this->getConfigData('active') && $this->cart->hasOnlyStockableItems();
```

**Comment by devansh-webkul** [comment]
Also please update the changelog in the unreleased section.

**Comment by devansh-webkul** [comment]
Thanks for the contribution! :rocket:

**Comment by og-khushalpatel** [comment]
> Thanks for the contribution! 🚀

Thanks for the review and merge! Looking forward to contributing more.
