### PR TITLE
Fixed #3974 (Validation Message Shown now)

### LINKED ISSUE #3974: No validation message shown on updating customer profile page
# Bug report

When I am trying to update a customer with API and I am not filling the required parameters. Then, it gives me the user details instead of the validation error message.

- If somehow I am able to update the profile. It gives me the message for account creation instead of account updation,

    Screenshot from 2020-09-28 14-14-15

### Preconditions

    1. Framework Version: Master

### Steps to reproduce

    1. Try to update the customer profile with API.

### Expected result

   1. If I am not filling the required parameters then it should give me the validation error message with proper status code.
   2. Update message should be shown.

### PR DESCRIPTION
**Pull request by JunaidJaved8461**
**BUGS:**

>Please describe the issue that you solved if its not filed.

>Otherwise please mention issue #id and use comma if your PR
>solves multiple issues.
I have fixed **issue #id** by keeping the existing code of conduct.
Another method that we can fix it by using
    $validator = Validator::make($request->all(), [
          'first_name'    => 'required',
            'last_name'     => 'required',
            'gender'        => 'required',
            'date_of_birth' => 'nullable|date|before:today',
            'email'         => 'email|unique:customers,email,' . $customer->id,
            'password'      => 'confirmed|min:6',
        ]);

        if ($validator->fails()) {
            return redirect()
                        ->withErrors($validator)
                        ->withInput();
        }
**For things other than bugs:**

> Describe that thing in very short line, word limit is 200.

> Otherwise use **issue #id** if the issue was filed as **feature** request.

### CODE REVIEW

**Comment by devansh-webkul** [comment]
Hi @JunaidJaved8461,

As I am seeing the code `date_of_birth` field is `nullable`. So, I didn't send `date_of_birth` and I generated this issue. Please resolve this also.

Screenshot from 2020-10-09 13-37-57

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php [hunk 1]
```diff
@@ -103,7 +103,7 @@ public function update()
             'password'      => 'confirmed|min:6',
         ]);
 
-        $data = request()->all();
+        $data = request()->only('first_name','last_name','gender','date_of_birth','email','password');
```
Comment (devansh-webkul) [inline packages/Webkul/API/Http/Controllers/Shop/SessionController.php:106]: Add one space after each comma.

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php [hunk 2]
```diff
@@ -103,7 +103,7 @@ public function update()
...
 
         if (! $data['date_of_birth']) {
```
Comment (devansh-webkul) [inline packages/Webkul/API/Http/Controllers/Shop/SessionController.php:108]: Can, you please just remove these three lines because validation portion is handling `date_of_birth`. So not needed anymore.

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php [hunk 3]
```diff
@@ -118,7 +118,7 @@ public function update()
         $this->customerRepository->update($data, $customer->id);
```
Comment (devansh-webkul) [inline packages/Webkul/API/Http/Controllers/Shop/SessionController.php:118]: Just assign this to `$updatedCustomer`.

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php [hunk 4]
```diff
@@ -118,7 +118,7 @@ public function update()
...
 
         return response()->json([
-            'message' => 'Your account has been created successfully.',
+            'message' => 'Your account has been updated successfully.',
             'data'    => new CustomerResource($this->customerRepository->find($customer->id)),
```
Comment (devansh-webkul) [inline packages/Webkul/API/Http/Controllers/Shop/SessionController.php:122]: And pass that `$updatedCustomer` here rather than one more find query.

**Review by devansh-webkul — COMMENTED** [review]
So far fine, just final method finishing needed.

**Comment by devansh-webkul** [comment]
Hi @JunaidJaved8461,

Some small changes and method enhancement needed.

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php [hunk 5]
```diff
@@ -38,6 +38,9 @@ public function __construct(CustomerRepository $customerRepository)
         $this->_config = request('_config');
 
         $this->customerRepository = $customerRepository;
+        
+        $this->updatedCustomer = $customerRepository;
+
```
Comment (devansh-webkul) [inline packages/Webkul/API/Http/Controllers/Shop/SessionController.php:43]: Not Here.

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php [hunk 6]
```diff
@@ -103,23 +106,19 @@ public function update()
...
+        $data = request()->only('first_name', 'last_name', 'gender', 'date_of_birth', 'email', 'password');
 
         if (!isset($data['password']) || ! $data['password']) {
             unset($data['password']);
         } else {
             $data['password'] = bcrypt($data['password']);
         }
 
-        $this->customerRepository->update($data, $customer->id);
+        $this->updatedCustomer->update($data, $customer->id);
```
Comment (devansh-webkul) [inline packages/Webkul/API/Http/Controllers/Shop/SessionController.php:117]: Only here,
`$updatedCustomer = $this->customerRepository->update($data, $customer->id);`

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php [hunk 7]
```diff
@@ -103,23 +106,19 @@ public function update()
...
 
         return response()->json([
             'message' => 'Your account has been updated successfully.',
-            'data'    => new CustomerResource($this->customerRepository->find($customer->id)),
+            'data'    => new CustomerResource($this->updatedCustomer->find($customer->id)),
```
Comment (devansh-webkul) [inline packages/Webkul/API/Http/Controllers/Shop/SessionController.php:121]: Pass here,

`new CustomerResource($updatedCustomer)`

**Comment by devansh-webkul** [comment]
@JunaidJaved8461,

Not in the constructor, just check one more time.

**Review by devansh-webkul — COMMENTED** [review]
@JunaidJaved8461,

Not in the constructor, just check one more time.

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php [hunk 8]
```diff
@@ -38,6 +38,7 @@ public function __construct(CustomerRepository $customerRepository)
         $this->_config = request('_config');
 
         $this->customerRepository = $customerRepository;
+
```
Comment (devansh-webkul) [inline packages/Webkul/API/Http/Controllers/Shop/SessionController.php:41]: Remove one line from here.

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php [hunk 9]
```diff
@@ -103,23 +104,19 @@ public function update()
...
         ]);
 
-        $data = request()->all();
-
-        if (! $data['date_of_birth']) {
-            unset($data['date_of_birth']);
-        }
+        $data = request()->only('first_name', 'last_name', 'gender', 'date_of_birth', 'email', 'password');
 
         if (!isset($data['password']) || ! $data['password']) {
```
Comment (devansh-webkul) [inline packages/Webkul/API/Http/Controllers/Shop/SessionController.php:109]: Add space after '!' i.e. `! isset($data['password']) || ! $data['password']`

**Review by devansh-webkul — COMMENTED** [review]
One last change needed.

File: packages/Webkul/API/Http/Controllers/Shop/SessionController.php (hunk 8 above)
Comment (JunaidJaved8461) [reply packages/Webkul/API/Http/Controllers/Shop/SessionController.php:41]: sorry can't get it which line?

Comment (devansh-webkul) [reply packages/Webkul/API/Http/Controllers/Shop/SessionController.php:41]: Empty Line Line Number 41.

**Review by devansh-webkul — APPROVED** [review]
