### PR TITLE
Fixed #8683

### LINKED ISSUE #8683: If the address is added as default and while the customer updates that particular address it removes the default address.
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

If the address is added as default and while the customer updates that particular address it removes the default address.

### Preconditions

1. Customer must be logged in.
2. Customer should have at least one added address and set it as default.

### Steps to reproduce

1. Go to 'Shop' and login as User
2. Edit the default address and save it inside the Accounts/Addresses
3. See the error

### Expected Result

It should be saved as the default address until the user does not set another address as default or deletes that address.

### Actual Result

After updating the address it was removed as the default address.  [Here](https://webkul.chatwhizz.com/share/view-recording/652d3555ea63c532cde30324)

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JunaidJaved248**
## Issue Reference
#8683 

## Description
For fixing #8683  Set existing default_address bit on update address, (prevent to set default address 0) 

## How To Test This?
Customer must be logged in.
Customer should have at least one added address and set it as default.
Go to 'Shop' and login as User
Edit the default address and save it inside the Accounts/Addresses

### CODE REVIEW

**Comment by Amitk-webkul** [comment]
@JunaidJaved248 It is working fine.

File: packages/Webkul/Customer/src/Repositories/CustomerAddressRepository.php [hunk 1]
```diff
@@ -49,7 +49,7 @@ public function update(array $data, $id)
     {
         $address = $this->find($id);
 
-        $data['default_address'] = isset($data['default_address']);
+        $data['default_address'] = isset($data['default_address']) ? $data['default_address'] : $address->default_address;
```
Comment (amit-webkul) [inline packages/Webkul/Customer/src/Repositories/CustomerAddressRepository.php:52]: Here, we can use the null coalescing operator.

**Review by amit-webkul — APPROVED** [review]

**Review by devansh-webkul — APPROVED** [review]

**Review by jitendra-webkul — APPROVED** [review]
